CREATE SCHEMA DM_TIMETABLE;

CREATE ROLE DM_TIMETABLE_R;
CREATE ROLE DM_TIMETABLE_W;
CREATE ROLE DM_TIMETABLE_A;


GRANT USAGE ON SCHEMA DM_TIMETABLE TO DM_TIMETABLE_R, DM_TIMETABLE_W;
GRANT CREATE, USAGE ON SCHEMA DM_TIMETABLE TO DM_TIMETABLE_A;

GRANT SELECT ON SCHEMA DM_TIMETABLE TO DM_TIMETABLE_R;
GRANT UPDATE, DELETE, TRUNCATE, INSERT ON SCHEMA DM_TIMETABLE TO DM_TIMETABLE_W;
GRANT CREATE, SELECT, INSERT, UPDATE, TRUNCATE, DELETE, REFERENCES ON SCHEMA DM_TIMETABLE TO DM_TIMETABLE_A;
GRANT ALTER, DROP ON SCHEMA DM_TIMETABLE TO DM_TIMETABLE_A;
