CREATE SCHEMA STG_TIMETABLE;

CREATE ROLE STG_TIMETABLE_R;
CREATE ROLE STG_TIMETABLE_W;
CREATE ROLE STG_TIMETABLE_A;


GRANT USAGE ON SCHEMA STG_TIMETABLE TO STG_TIMETABLE_R, STG_TIMETABLE_W;
GRANT CREATE, USAGE ON SCHEMA STG_TIMETABLE TO STG_TIMETABLE_A;

GRANT SELECT ON SCHEMA STG_TIMETABLE TO STG_TIMETABLE_R;
GRANT UPDATE, DELETE, TRUNCATE, INSERT ON SCHEMA STG_TIMETABLE TO STG_TIMETABLE_W;
GRANT CREATE, SELECT, INSERT, UPDATE, TRUNCATE, DELETE, REFERENCES ON SCHEMA STG_TIMETABLE TO STG_TIMETABLE_A;
GRANT ALTER, DROP ON SCHEMA STG_TIMETABLE TO STG_TIMETABLE_A;
